### ISSUE TITLE
Sync with version on https://sforgcompare.herokuapp.com/

### ISSUE THREAD

**Issue by JAertgeerts** [benedwards44/sforgcompare#2]
Code seems to be an outdated version of the sforgcompare.herokuapp.com

Any chances of updating?

**Comment by benedwards44** [comment]
Hey mate, just looking at your Pull Request now. I think the repo is a bit
behind what is actually running on Heroku, so I will update that first. 

Eg. I am using environment variables for a lot of the settings now and the API version is 34.0 etc.

I think updating Django to 1.9.6 will break the app, so might need to test
that offline. Apart from that, I like the other changes.

Let me update it from Heroku and I'll let you know.

On 21 May 2016 at 10:55, Jan Aertgeerts notifications@github.com wrote:

> Code seems to be an outdated version of the sforgcompare.herokuapp.com
> 
> Any chances of updating?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/benedwards44/sforgcompare/issues/2

## 

Ben Edwards
+64 21 707 236

**Comment by JAertgeerts** [comment]
Great to hear! Looking forward to the update.
Are you planning to open source the doctor? Would love to contribute.

**Comment by benedwards44** [comment]
No sorry @JAertgeerts , I didn't write the Org Doctor app so wasn't comfortable opening it up. It was done by an ex-colleague of mine.
