### ISSUE TITLE
Deploying to Heroku fails

### ISSUE THREAD

**Issue by timbarsotti** [benedwards44/sforgcompare#5]
Not sure if I'm doing something wrong or if this is a deployment bug. 

During the "Run scripts & scale dynos" step receiving the error:
Postdeploy exit code was not 0
bash: manage.py: command not found

**Comment by benedwards44** [comment]
@timbarsotti I've just updated the app.json file which I think should fix this issue. Looks like the script was executing `manage.py syncdb` rather than `python manage.py syncdb`

Try it again and let me know.
