### ISSUE TITLE
Cannot login to Sandbox for Org One in Salesforce Org Compare Tool

### ISSUE THREAD

**Issue by mazz44** [benedwards44/sforgcompare#6]
Hi. I created two empty sandboxes in two different Salesforce instances for the meta data compare. I can login to the sandbox for Org Two. But I cannot login to the Sandbox in Org One. I tried the reverse of Sandboxes for Org One and Two so I know the sandbox login and access works. It's just that when I select Org One and Sandbox it does not complete the login.

**Comment by benedwards44** [comment]
Hey, do you get any error messages? Seems to be working for me and  I haven't had anyone else with this issue.

Can you try in cognito mode in Chrome? Only thing I can think of it it's cached a login from already been logged into a Salesforce instance.
